#define MOTOR_LEFT_FRONT D2, D1
#define MOTOR_LEFT_REAR D8, D7

#define MOTOR_RIGHT_FRONT D4, D3
#define MOTOR_RIGHT_REAR D10, D9

#define START_BYTE 0xAA
#define SET_MOTOR_SPEED 0x01
#define COMMAND_SIZE 5

#define ARM_SERVO D0
#define CLAW_TOUCH D5
#define CLAW D6