#define MOTOR_LEFT_FRONT D2, D3
#define MOTOR_LEFT_REAR D4, D5

#define MOTOR_RIGHT_FRONT D6, D7
#define MOTOR_RIGHT_REAR D9, D10

#define START_BYTE 0xAA
#define SET_MOTOR_SPEED 0x01
#define COMMAND_SIZE 5

#define ARM_SERVO D0
#define CLAW_TOUCH D1
#define CLAW D8