[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
upload_speed = 115200
build_src_filter = +<*> -<test_single_motor.cpp> -<test_motor_pairs.cpp> -<test_all_idle.cpp> -<test_servo_scan.cpp> -<test_noise_combo.cpp> -<test_pwm_all.cpp>

; [env:esp32dev_singlemotor]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 921600
; build_src_filter = +<test_single_motor.cpp>

; [env:esp32dev_pairtest]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 921600
; build_src_filter = +<test_motor_pairs.cpp>

; [env:esp32dev_pwmall]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 921600
; build_src_filter = +<test_pwm_all.cpp> +<Motor.cpp>

; [env:esp32dev_idle]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 921600
; build_src_filter = +<test_all_idle.cpp>

; [env:esp32dev_servoscan]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 921600
; build_src_filter = +<test_servo_scan.cpp>

; [env:esp32dev_noisecombo]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 921600
; build_src_filter = +<test_noise_combo.cpp> +<Motor.cpp>
